TOPDIR=./../..

LIB=libq_reverse.a

INCPATH+=$(TOPDIR)/include/q_print
INCPATH+=$(TOPDIR)/include/q_share
INCPATH+=$(TOPDIR)/include/q_reverse
LIBPATH=$(TOPDIR)/lib
CFLAGS= -I$(INCPATH)

include $(TOPDIR)/Makefile.env
