TOPDIR=./../..

LIB=libq_reverse.a

INCPATH+=-I$(TOPDIR)/include/q_share
INCPATH+=-I$(TOPDIR)/include/q_list
INCPATH+=-I$(TOPDIR)/include/q_vector
INCPATH+=-I$(TOPDIR)/include/q_fibonacci
INCPATH+=-I$(TOPDIR)/include/q_print
INCPATH+=-I$(TOPDIR)/include/q_share
INCPATH+=-I$(TOPDIR)/include/q_reverse
CFLAGS= $(INCPATH)

LIBPATH=$(TOPDIR)/lib

include $(TOPDIR)/Makefile.env
