TOPDIR=./../..

LIB=libq_random.a

INCPATH+=-I$(TOPDIR)/include/q_print
INCPATH+=-I$(TOPDIR)/include/q_vector
INCPATH+=-I$(TOPDIR)/include/q_list
INCPATH+=-I$(TOPDIR)/include/q_fibonacci
INCPATH+=-I$(TOPDIR)/include/q_random
INCPATH+=-I$(TOPDIR)/include/q_share

#INCPATH+=$(TOPDIR)/include/q_print
#INCPATH+=$(TOPDIR)/include/q_vector
#INCPATH+=$(TOPDIR)/include/q_random


LIBPATH=$(TOPDIR)/lib
CFLAGS= $(INCPATH)
#CFLAGS= -I$(INCPATH)
#LDFLAGS+= -lq_sum

include $(TOPDIR)/Makefile.env
